[package]
name = "json_rs"
version = "0.1.0"
authors = []
edition = "2018"

[lib]
name = "json_rs"
path = "src/lib.rs"
crate-type = ["dylib"]

[dependencies]
serde = "1"
serde_json = "1"
rustler = "0.22.0-rc.0"

[profile.release]
codegen-units = 1
lto = true
